keys:
  - &server_pine age12p8e9ctkuu0qj3j3ka9tkaktn2k3prtrssfzcc8kdut0qsqxfs8sh0vukh
  - &server_sequoia age1ryrkhrdczkvcgs2tuvvlfy4qgsdelwjhthnm88hquv5hntplmplqfuxdm4
  - &admin_alex age1gkagt89wv3z4k3rxp5s0wqwaaml9mlvwfrzfzvh8fnjnwymarpzq5ccs67
  - &admin_liferooter age1w8gl68d3eanxk7s9fzahs7vlyxaj244uk8jcruw74l89c2dy7v5svj4tlp
  - &admin_khromotov age1t5l8qh0wuypede88y8u6lwqpux8cw3l7jkqn4ynahhgzs76eus4sr5r4e8
  - &admin_daryapvlv age143wc5gdeagg0nennue3yqrppn73pt8wek60s74y6j69cqsmacacqf90k5e
  - &admin_jepa age1ppf9k3fcjmdgsq9n99hman3ppukhdznml7xrpyawggscdhr8lqms0vhlnw
  - &admin_maxmaz age108cwl09e0qv2nl39w5kw0xqtqme3l5s8ttw8p8vhsekyslf0zfusskdmh6
creation_rules:
  - path_regex: modules/by-name/secrets/common.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *server_sequoia
          - *server_pine
  - path_regex: hosts/sequoia/wireguard-server.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *admin_khromotov
          - *admin_daryapvlv
          - *admin_jepa
          - *admin_maxmaz
          - *server_sequoia
  - path_regex: wireguard-clients.yml
    key_groups:
      - age:
          - *admin_alex
          - *admin_liferooter
          - *admin_khromotov
          - *admin_daryapvlv
          - *admin_jepa
          - *admin_maxmaz
          - *server_sequoia
